import React from 'react';
import { Database, Plus, Search, Landmark } from 'lucide-react';

export default function GeneralLedgerModule() {
  const ledgerEntries = [
    { code: '661100', account: 'Gross Salaries (Salaires bruts)', debit: '12 450 000 FCFA', credit: '0 FCFA', date: '2026-06-30' },
    { code: '421000', account: 'Personnel Payable (Personnel - Rémunérations dues)', debit: '0 FCFA', credit: '9 250 000 FCFA', date: '2026-06-30' },
    { code: '442100', account: 'Tax Withholding - IRPP (Etat - Impôts retenus source)', debit: '0 FCFA', credit: '1 850 000 FCFA', date: '2026-06-30' },
    { code: '431100', account: 'Social Security - CNPS (Sécurité Sociale)', debit: '0 FCFA', credit: '1 350 000 FCFA', date: '2026-06-30' },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h3 className="font-display font-black text-slate-900 text-lg">General Ledger & Double-Entry Journal</h3>
          <p className="text-xs text-zinc-500 font-medium">Verify automated ledger entries generated by monthly payroll compliance cycles</p>
        </div>
      </div>

      <div className="bg-white border border-zinc-150 rounded-3xl overflow-hidden shadow-[0_8px_30px_rgba(0,0,0,0.01)]">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-zinc-50 border-b border-zinc-150 text-zinc-500 font-bold uppercase tracking-wider text-[10px]">
                <th className="p-4 pl-6">Account Code</th>
                <th className="p-4">Account Label</th>
                <th className="p-4">Debit</th>
                <th className="p-4">Credit</th>
                <th className="p-4 pr-6">Posting Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-zinc-100 text-zinc-700 font-medium">
              {ledgerEntries.map((entry, idx) => (
                <tr key={idx} className="hover:bg-zinc-50/50 transition-colors">
                  <td className="p-4 pl-6 font-mono font-bold text-[#7c3aed]">{entry.code}</td>
                  <td className="p-4 font-semibold text-zinc-900">{entry.account}</td>
                  <td className="p-4 font-mono font-semibold text-violet-700">{entry.debit}</td>
                  <td className="p-4 font-mono font-semibold text-zinc-600">{entry.credit}</td>
                  <td className="p-4 pr-6 text-zinc-500">{entry.date}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
